
spring:

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: na
    password:

  jpa:
    generate-ddl: true
    hibernate:
      ddl_auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    root: info
    com.elyo.nbox : debug